config/routes.rb
Rails.application.routes.draw do
  get '/clip', to: 'clip#index'
  post '/clip/upload_clip', to: 'clip#upload_clip'
  post '/clip/upload_image', to: 'clip#upload_image'
  post '/clip/upload_text', to: 'clip#upload_text'

  get 'responsive/index'

  get '/keywords/', to: 'key_word#index'
  post '/keywords/check', to: 'key_word#check'

  get 'text/index'

  post 'text/check'

  get 'banner/index'

  post 'banner/upload', to: 'banner#check'

  post 'responsive/upload', to: 'responsive#file_check'

  post 'responsive/textcheck', to: 'responsive#text_check'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'text#index'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RegulationCheck</title>
  <%= csrf_meta_tags %>
  <%= yield(:css) %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', controller.controller_name, 'data-turbolinks-track': 'reload' %>
  <%= yield(:js) %>
</head>

<body>
<div class="menu fixed">
  <div class="col-md-3 col-xl-3 col-xs-3">
    <a href="#" id="logo">
      <%= image_tag 'logo.png' %>
    </a>
  </div>
  <div id="nav" class="col-md-6 col-xs-6 col-xl-6">
    <div class="sliding-line" id="line-top" style="display: none;"></div>
    <ul class="navigation">
      <li href="<%= banner_index_path %>" page-slide="1" class="
                <% if @is_banner_active %>active
                <% end %>">
            バナー広告
      </li>
      <li href="<%= text_index_path %>" page-slide="2" class="
                <% if @is_text_active %>active
                <% end %>">
            テキスト広告
      </li>
      <li href="<%= keywords_path %>" page-slide="3" class="
                <% if @is_keyword_active %>active
                <% end %>">
        キーワード
      </li>
      <li href="<%= responsive_index_path %>" page-slide="4" class="
                <% if @is_responsive_active %>active
                <% end %>">
        レスポンシブ広告
      </li>
      <li href="<%= clip_path %>" page-slide="5" class="
                <% if @is_clip_active %>active
                <% end %>">
        YDN動画広告
      </li>
    </ul>
    <div class="sliding-line" id="line-bottom" style="display: none;"></div>
  </div>
</div>
<div class="loader"></div>
<div class="content"><%= yield %></div>
</body>
</html>